tracker_type: botsort
track_high_thresh: 0.35
track_low_thresh: 0.10
new_track_thresh: 0.25
track_buffer: 90
match_thresh: 0.75
fuse_score: true
gmc_method: sparseOptFlow
with_reid: false
proximity_thresh: 0.5
appearance_thresh: 0.25
model: auto
